---
name: Package and Publish Helm Chart
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    if: github.repository == 'andrewrothstein/bazel-buildfarm'
    name: helm package and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
      - run: |-
          helm dep up kubernetes/helm-charts/buildfarm
          helm package kubernetes/helm-charts/buildfarm
          ls -l *.tgz
