---
name: Package and Publish Helm Chart
on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: github.repository == 'andrewrothstein/bazel-buildfarm'
    name: helm package and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: helm package
        run: |-
          set -ex
          helm dep up kubernetes/helm-charts/buildfarm
          helm package kubernetes/helm-charts/buildfarm
          ls -l *.tgz
          gh release create "${{ github.ref_name }}" buildfarm-0.1.0.tgz
